CIFAR_CLASSES: 10
layers: 8
auxiliary: False
auxiliary_weight: 0.4
init_channels: 16
arch: 'DARTS'
learning_rate: 0.025
momentum: 0.9
weight_decay: 0.0003
epochs: 1
drop_path_prob: 0.2
save: '/weight_samples/weights'
grad_clip: 5
n_classes: 10
input_channels: 3
aux_weight: 0.4
input_size: 32